### ISSUE TITLE
3.0.2 breaks sublime theme, plugins - AttributeError: 'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by sammcj** [mfuentesg/SyncSettings#115]
After updating from 3.0.1 to 3.0.2 my theme is all messed up and plugins not working.

- SyncSettings: 3.0.2
- Sublime: 3189
- macOS 10.14.3

The console is show lots of errors for Sync Settings after it updated:

```python
Traceback (most recent call last):
  File "/Users/samm/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "/Users/samm/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/logging/__init__.py", line 941, in emit
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 154: ordinal not in range(128)
Logged from file sync_manager.py, line 90
Traceback (most recent call last):
  File "/Users/samm/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "/Users/samm/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/logging/__init__.py", line 941, in emit
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 154: ordinal not in range(128)
Logged from file sync_manager.py, line 90
Traceback (most recent call last):
  File "/Users/samm/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "/Users/samm/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/logging/__init__.py", line 941, in emit
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 157: ordinal not in range(128)
Logged from file sync_manager.py, line 90
Traceback (most recent call last):
  File "/Users/samm/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "/Users/samm/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/logging/__init__.py", line 941, in emit
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 154: ordinal not in range(128)
Logged from file sync_manager.py, line 90
```

**Comment by mfuentesg** [comment]
sorry about that, i am going to figure out what is happening.
Can you send me your `gist_id` to try to replicate the behavior on my environment..
Thanks in advance!

**Comment by mfuentesg** [comment]
btw: this is the only change on the new release

https://github.com/mfuentesg/SyncSettings/commit/8b19d695160cb9aee1dbd988c8c089198b193e14

**Comment by sammcj** [comment]
NP,

Note: It may have upgraded from 3.0.0 to 3.0.2 and I missed it somehow.

My gist is a private one as it _could_ contain private data couldn't it?

**Comment by sammcj** [comment]
I keep it private in case I add something like identifiable IP addresses, hostnames, secrets or anything to any config by mistake.

It's got a _lot_ of files / data in it - having a quick look through it seems OK, but I'd rather not publish publicly - do you use signal or twitter? I could DM you a password and email you an encrypted archive of it just to be safe.

**Comment by mfuentesg** [comment]
@sammcj please check your DM on twitter!

**Comment by neo2271** [comment]
@mfuentesg: I have also met this issue.

ERROR:Sync Settings.sync_settings.libs.logger:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'
WARNING:Sync Settings.sync_settings.libs.logger:can`t edit file `C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Packages\User\oscrypto-ca-bundle.crt`
ERROR:Sync Settings.sync_settings.libs.logger:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'
WARNING:Sync Settings.sync_settings.libs.logger:can`t edit file `C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Packages\User\bh_core.sublime-settings`
ERROR:Sync Settings.sync_settings.libs.logger:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'
WARNING:Sync Settings.sync_settings.libs.logger:can`t edit file `C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.last-run`
ERROR:Sync Settings.sync_settings.libs.logger:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'
WARNING:Sync Settings.sync_settings.libs.logger:can`t edit file `C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Packages\User\Side Bar.sublime-settings`
ERROR:Sync Settings.sync_settings.libs.logger:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'
WARNING:Sync Settings.sync_settings.libs.logger:can`t edit file `C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Packages\User\SublimeCodeIntel.sublime-settings`
ERROR:Sync Settings.sync_settings.libs.logger:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'
WARNING:Sync Settings.sync_settings.libs.logger:can`t edit file `C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Packages\User\Terminal.sublime-settings`
ERROR:Sync Settings.sync_settings.libs.logger:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'
WARNING:Sync Settings.sync_settings.libs.logger:can`t edit file `C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.cache\01524fae79697630d0454ba3fabd9414`
ERROR:Sync Settings.sync_settings.libs.logger:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'
WARNING:Sync Settings.sync_settings.libs.logger:can`t edit file `C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Packages\User\_sublime-text-sync-settings`
ERROR:Sync Settings.sync_settings.libs.logger:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'
WARNING:Sync Settings.sync_settings.libs.logger:can`t edit file `C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.merged-ca-bundle`
ERROR:Sync Settings.sync_settings.libs.logger:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'
WARNING:Sync Settings.sync_settings.libs.logger:can`t edit file `C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Packages\User\bh_tag.sublime-settings`
ERROR:Sync Settings.sync_settings.libs.logger:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'
WARNING:Sync Settings.sync_settings.libs.logger:can`t edit file `C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.cache\01524fae79697630d0454ba3fabd9414.info`
ERROR:Sync Settings.sync_settings.libs.logger:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'
WARNING:Sync Settings.sync_settings.libs.logger:can`t edit file `C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Packages\User\sublime-text-sync-settings`
ERROR:Sync Settings.sync_settings.libs.logger:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'
WARNING:Sync Settings.sync_settings.libs.logger:can`t edit file `C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Packages\User\SublimeLinter.sublime-settings`
ERROR:Sync Settings.sync_settings.libs.logger:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'
WARNING:Sync Settings.sync_settings.libs.logger:can`t edit file `C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Packages\User\SBSCompareTheme.tmTheme`
ERROR:Sync Settings.sync_settings.libs.logger:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'
WARNING:Sync Settings.sync_settings.libs.logger:can`t edit file `C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Packages\User\clang_format.sublime-settings`
ERROR:Sync Settings.sync_settings.libs.logger:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "C:\Users\ADMIN\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'

**Comment by mfuentesg** [comment]
Guys, please change your package control settings using the `install_prerelease` setting to include `Sync Settings` and use the pre release that I have created, then, try to download your settings again.

Thanks in advance

**Comment by mfuentesg** [comment]
Let me know if the issue is still alive.

**Comment by sammcj** [comment]
Thanks @mfuentesg , testing now.

FYI for @neo2271 - in the sublime command pallet open "Preferences Package control settings - user"

remove `"Sync Settings"` from the list of `"install_packages"` and add:

```json
	"install_prereleases":[
	  "Sync Settings"
	],
```

**Comment by neo2271** [comment]
Great! That's ok. It worked, now I can sync my settings from other machine.

Thanks @mfuentesg for the great Sublime Text package.

Thanks @sammcj for your help.

(y)

**Comment by sammcj** [comment]
@mfuentesg same problem 😢 

I did get a popup error saying colourcoder (an awesome package) couldn't pass the colourscheme while syncsettings was downloading settings but I've noticed the odd error here and there in the past when first installing packages and they haven't got their dependencies yet.

However, the same python error with syncsettings and utf8 is there, here are some screenshots:

- Error during package installation (I'd say this is normal if it hasn't finished being installed / dependencies etc...):

![screen shot 2019-02-14 at 5 29 00 pm](https://user-images.githubusercontent.com/862951/52767405-819be180-307e-11e9-8477-1d3ddad7f70c.jpg)

- Error with syncsettings:

![screen shot 2019-02-14 at 5 29 23 pm](https://user-images.githubusercontent.com/862951/52767433-98dacf00-307e-11e9-8bca-fb9d78f2222f.jpg)

- Full console output:

```
Unable to open /Users/samm/Library/Application Support/Sublime Text 3/Packages/Default/Preferences.sublime-settings
Detected ASCII vs Undefined with 100% confidence
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Settings change detected, clearing cache
ignored packages updated to: ["Sync Settings", "Vintage"]
unloading plugin Sync Settings.1_reloader
unloading plugin Sync Settings.SyncSettings
reloading settings Packages/Sync Settings/SyncSettings.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading /Users/samm/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings
reloading /Users/samm/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading /Users/samm/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin Sync Settings.1_reloader
reloading plugin Sync Settings.SyncSettings
reloading settings Packages/Sync Settings/SyncSettings.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading /Users/samm/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings
reloading /Users/samm/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading /Users/samm/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings
Package Control: All dependencies have been satisfied
reloading settings Packages/User/Preferences.sublime-settings
reloading /Users/samm/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading /Users/samm/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings

Traceback (most recent call last):
  File "/Users/samm/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "/Users/samm/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/logging/__init__.py", line 941, in emit
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 154: ordinal not in range(128)
Logged from file sync_manager.py, line 90
Traceback (most recent call last):
  File "/Users/samm/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "/Users/samm/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/logging/__init__.py", line 941, in emit
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 154: ordinal not in range(128)
Logged from file sync_manager.py, line 90
Traceback (most recent call last):
  File "/Users/samm/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "/Users/samm/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/logging/__init__.py", line 941, in emit
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 157: ordinal not in range(128)
Logged from file sync_manager.py, line 90
Traceback (most recent call last):
  File "/Users/samm/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "/Users/samm/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/logging/__init__.py", line 941, in emit
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 154: ordinal not in range(128)
Logged from file sync_manager.py, line 90
reloading settings Packages/User/ApplySyntax.ext-list
reloading settings Packages/User/ApplySyntax.sublime-settings
reloading settings Packages/User/Bash.sublime-settings
reloading settings Packages/User/GitGutter.sublime-settings
reloading settings Packages/User/HTML (Rails).sublime-settings
reloading settings Packages/User/INI.sublime-settings
reloading settings Packages/User/JSON.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/SyncSettings.sublime-settings
error: Colorcoder was not able to parse the colorscheme
Check the console for the actual error message.
resource not found
reloading /Users/samm/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings
reloading /Users/samm/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings
reloading settings Packages/User/ApplySyntax.ext-list
reloading settings Packages/User/Bash.sublime-settings
```

**Comment by sammcj** [comment]
I thought I'd rule out colourcoder so I did the following (which shows it's not colourcoder):

1. Removing colourcoder package from work machine, upload sync settings
2. Close and reopen sublimetext on home machine
3. Download sync settings on home machine

SyncSettings now pops up with these errors:

![screen shot 2019-02-14 at 5 40 04 pm](https://user-images.githubusercontent.com/862951/52767783-9af15d80-307f-11e9-8aa7-7447d25e0811.jpg)

And as I keep clicking OK more and more packages show up in the ignored package list until sublime crashed:

![screen shot 2019-02-14 at 5 40 50 pm](https://user-images.githubusercontent.com/862951/52767827-ba888600-307f-11e9-95b2-9aa17227ca7a.jpg)

- I then re-opened sublime, ran download sync settings it finished download.

...but all the packages are in ignored (as pictured above), the theme isn't applied and all my settings are missing - so I don't think it actually did download anything and no console / errors were thrown.

- I then closed and reopened sublimetext and removed all the packages listed in the ignore packages list, then I got the same errors about packages trying to ignore itself, as I kept hitting OK I kept getting a beachball of death (on a brand new i9 2018 top-spec MBP!) and I keep clicking OK and they keep getting added back into ignored packages:

![screen shot 2019-02-14 at 5 45 58 pm](https://user-images.githubusercontent.com/862951/52768065-70ec6b00-3080-11e9-95c7-70ff71d9f1b5.jpg)

So it actually seems worse now as there are now no user settings and all packages are ignored.

**Comment by sammcj** [comment]
I just tested again this time:

1. Completely remove sublime text and Application\ Support/Sublime\ Text\ 3 directory
2. Install sublime text 3
3. Install package manager
4. Install sync settings (prerelease)
5. Update gist in sync settings settings
6. Download sync settings

This time a new pop-up error:

![screen shot 2019-02-14 at 5 58 04 pm](https://user-images.githubusercontent.com/862951/52768677-3edc0880-3082-11e9-864a-e1ca1d2f3e8a.jpg)

**Comment by sammcj** [comment]
OK I'm getting somewhere... (writing this as it's happening)

1. I did another clean install of sublimetext on my home machine (entered license)
2. Installed (prerelease) sync settings
3. Filled out sync settings gist
4. Copied the contents of my package control settings file from my work machine to my home machine
5. Ran sync settings download
6. All my packages are now downloading without error (I'm getting their post-install info etc...)
7. Got one popup for the recursively trying to ignore itself, but clicked OK and the install is continuing...
8. After a bunch more packages installed got another of the same popups, again clicked ok and it's continuing...
9. All packages finished downloading
10. Checked my settings and... they're blank! (see below snippet)

So, by pre-adding the list of packages to the installed package list (without installing them) seemed to fix the download and install problem, but now settings are still blank?

```
{
	"ignored_packages":
	[
		"Vintage"
	]
}
```

**Comment by sammcj** [comment]
BTW my Preferences.sublime-settings is as follows:

```
{
	"added_words":
	[
		"online",
		"Amodha",
		"devs",
		"sysadmin",
		"admin",
		"apps",
		"comms",
		"infoxchange",
		"gluster",
		"mnt",
		"offline",
		"codebase",
		"Refactor",
		"Infoxchange's",
		"Wikipedia",
		"richmond",
		"nagios",
		"nessus",
		"hiera",
		"redmine",
		"serv",
		"rstd",
		"kube",
		"svc",
		"centos",
		"eyaml",
		"https",
		"Hypervisor",
		"Hypervisors",
		"virtualisation",
		"autovacuum",
		"Supermicro",
		"datacentres",
		"virtualised",
		"hypervisor",
		"proactively",
		"uninstall",
		"config",
		"hypervisors",
		"rsyslog",
		"redhat",
		"xenserver",
		"hieradata",
		"prometheus",
		"localhost",
		"smcleod",
		"icinga",
		"etcd",
		"packagecloud",
		"Kubernetes",
		"Citrix",
		"performant",
		"Office365",
		"Google",
		"setup",
		"xsconsole",
		"metadata",
		"cron",
		"systemctl",
		"glusterd",
		"max",
		"glusterfs",
		"glusterfsd",
		"killall",
		"Snapshotted",
		"tmp",
		"uninstalled",
		"Debian",
		"laggy",
		"Github",
		"Jira",
		"distro",
		"Dom0",
		"Xen",
		"distros",
		"repos",
		"stateful",
		"tapdisk",
		"Proxmox",
		"Redhat's",
		"pxeboot",
		"Plugin"
	],
	"additional_path_items":
	[
		"/Users/samm/.rvm/gems/default/bin",
		"/usr/local/bin",
		"/usr/bin"
	],
	"always_show_minimap_viewport": true,
	"animation_enabled": false,
	"bold_folder_labels": true,
	"color_scheme": "Packages/Edge Theme/Edge Night Sky.tmTheme",
	"dictionary": "Packages/Language - English/en_GB.dic",
	"drag_text": false,
	"edge_sidebar_font_small": false,
	"edge_use_font_face": true,
	"edge_use_sidebar_folder_icons": true,
	"fade_fold_buttons": true,
	"font_face": "IBM Plex Mono ExtraLight",
	"font_options":
	[
		"subpixel_antialias"
	],
	"font_size": 14,
	"hide_build_panel": "no_errors",
	"highlight_line": true,
	"highlight_modified_tabs": true,
	"hot_exit": false,
	"ignored_packages":
	[
		"Vintage"
	],
	"ignored_words":
	[
		"refactoring"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"indent_to_bracket": true,
	"index_exclude_patterns":
	[
		"*.log",
		"*.sql"
	],
	"line_padding_bottom": 2,
	"line_padding_top": 2,
	"margin": 2,
	"open_files_in_new_window": false,
	"original_color_scheme": "Packages/Edge Theme/Edge Night Sky.tmTheme",
	"overlay_scroll_bars": "enabled",
	"remember_open_files": false,
	"show_encoding": true,
	"show_line_endings": true,
	"show_sidebar": true,
	"show_tab_close_buttons": false,
	"spell_check": false,
	"status_bar_brighter": true,
	"sublimelinter_executable_map":
	{
		"ruby": "/Users/samm/.rvm/bin/rvm-auto-ruby"
	},
	"tab_completion": false,
	"tab_size": 2,
	"tabs_small": true,
	"theme": "Edge Night Sky.sublime-theme",
	"translate_tabs_to_spaces": true,
	"tree_animation_enabled": false,
	"word_wrap": true
}
```

**Comment by mfuentesg** [comment]
@sammcj  @neo2271 guys, please check the new version and let me know if the issue was solved.

**Comment by mfuentesg** [comment]
@sammcj , checking your screenshots, `a package is trying to ignore itself` is an open issue on package control repository, because i am using `advanced_install` command.

ref: https://github.com/wbond/package_control/issues/1191

**Comment by sammcj** [comment]
Sorry having an crazy day - I haven’t had a chance to test again - hopefully tomorrow afternoon, very sorry!

--
Sam McLeod

**Comment by sammcj** [comment]
Just got home and tested.

1. I updated the sync settings package.
2. I tested with my existing working config and plugins from my workaround yesterday.
3. I downloaded sync settings.
4. I got the following popup from sync settings:

![screen shot 2019-02-15 at 4 58 46 pm](https://user-images.githubusercontent.com/862951/52837562-56c79100-3143-11e9-955f-e7b8ea0e0aad.jpg)

5. I clicked OK and sync settings finished without error.

Then I tested to make sure the settings were being synced:

1. I removed all content from my Sublime preferences.
2. I downloaded sync settings.
3. I checked my preferences to make sure they were synced - they _weren't_:

![screen shot 2019-02-15 at 4 59 26 pm](https://user-images.githubusercontent.com/862951/52837609-85456c00-3143-11e9-8d3e-f5c4f71c949e.jpg)

**Comment by mfuentesg** [comment]
@sammcj i have tested with your gist, but a can download each file, and the preferences file was updated.

**Comment by mfuentesg** [comment]
could you paste here the logs, please!

**Comment by sammcj** [comment]
Sorry had a crazy weekend with a very nasty failed Juniper SRX1500 upgrade (the official process literally bricked a unit!), I'll try this out again tonight and provide logs if I'm still alive when I get home.

**Comment by mfuentesg** [comment]
@sammcj could you tell if the error has been fixed?

**Comment by sammcj** [comment]
whoops sorry - not it hasn't while it looks like packages are sync - settings (user preferences are not), is there a specific log I could provide you to help?

**Comment by mfuentesg** [comment]
Check your package control settings, and remove sync settings from your "pre release". Then run the command "show logs" and paste the file content here.

**Comment by sammcj** [comment]
It works! It all appears to work!

Thank you so much @mfuentesg 🍻

**Comment by mfuentesg** [comment]
Cool, thanks Sam!
